language: node_js
node_js: v12.4.0

# S: Build Lifecycle
install:
  - npm install && npm install gitbook -g && npm install -g gitbook-cli


script:
  - hexo clean && hexo g


after_script:
  - bash push_master.sh
# E: Build LifeCycle

branches:
  only:
    - blog_source
env:
  global:
    - GH_REF: github.com/turinglv/turinglv.github.io.git

notifications:
  email:
    recipients:
      - 332361566@qq.com